name: flutter_suncalc
description: A port of the suncalc library from https://github.com/mourner/suncalc
version: 0.1.0
homepage: https://github.com/shanus

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
# flutter:


